[workspace]
members = [
    "aabb_lib/runner",
    "agglom_lib/runner",
    "arr_del_lib/runner",
    "arr_ins_lib/runner",
    "arr_push_lib/runner",
    "basename_lib/runner",
    "call_predict_lib/runner",
    "capsule_lib/runner",
    "circle_collide_lib/runner",
    "cJSON_lib/runner",
    "convert_pix_lib/runner",
    "decode_base64_lib/runner",
    "encode_base64_lib/runner",
    "file_queue_lib/runner",
    "gen_ray_lib/runner",
    "get_predict_func_lib/runner",
    "gjk_cache_lib/runner",
    "gjk_lib/runner",
    "helxo_lib/runner",
    "hm_geti_lib/runner",
    "intput_lib/runner",
    "lines_in_buffer_lib/runner",
    "load_png_mem_lib/runner",
    "omni_collide_lib/runner",
    "omni_manifold_lib/runner",
    "parse_number_lib/runner",
    "parse_uname_lib/runner",
    "pinflate_lib/runner",
    "poly_ray_lib/runner",
    "rdg_genstdout_lib/runner",
    "reverse_collide_lib/runner",
    "search_and_replace_lib/runner",
    "sh_geti_lib/runner",
    "sh_puts_lib/runner",
    "siphash_lib/runner",
    "spec_ray_lib/runner",
    "strdup_lib/runner",
    "str_dups_lib/runner",
    "str_put_lib/runner",
    "underhanded-c-nuke_lib/runner",
    "unfilter_lib/runner",
    "utf8_lib/runner",
]
resolver = "2"
