[package]
name = "driver"
version = "0.1.0"
edition = "2021"

[features]
default = ["add", "5"]
# OP cache variable values
add = []
sub = []
mul = []
# REPEAT cache variable values
"0" = []
"1" = []
"2" = []
"3" = []
"4" = []
"5" = []
"6" = []
"7" = []

[lib]
name = "driver"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "driver"
path = "src/main.rs"

[profile.release]
overflow-checks = false

[profile.dev]
overflow-checks = false

[workspace]
