[package]
name = "sphincs_plus"
version = "0.1.0"
edition = "2021"

[lib]
name = "sha2"
crate-type = ["cdylib"]
path = "src/lib.rs"

[features]
default = ["sha2", "robust", "192f"]

# Hash backends
haraka = []
sha2 = []
shake = []
blake = []

# THASH variants
robust = []
simple = []

# SECPAR variants
"128s" = []
"128f" = []
"192s" = []
"192f" = []
"256s" = []
"256f" = []

[dependencies]
aes = "0.8"

[dev-dependencies]
libloading = "0.8"

[profile.release]
opt-level = 3

[workspace]
