[workspace]
members = [
    "001_helloworld_lib/runner",
    "003_string_slicing_lib/runner",
    "004_nineality_sieve_lib/runner",
    "005_static_loop_lib/runner",
    "006_static_alias_lib/runner",
    "007_errno-pow_lib/runner",
    "008_long_run_lib/runner",
    "009_stack_buffer_overflow_lib/runner",
    "010_integer_overflow_lib/runner",
    "011_uninit_char_ptr_lib/runner",
    "012_uninit_int_ptr_lib/runner",
    "013_poor_quality_addition_lib/runner",
    "014_dead_code_lib/runner",
    "015_return_stack_buffer_lib/runner",
    "016_divide_by_zero_float_lib/runner",
    "017_signed_length_confusion_lib/runner",
    "018_stack_buffer_overflow_loop1_lib/runner",
    "019_integer_overflow_char_max_multiply_lib/runner",
    "020_stack_linked_list_lib/runner",
    "021_complex_goto_lib/runner",
    "022_stdlib_div_lib/runner",
    "023_struct_and_errno_lib/runner",
    "024_struct_and_static_lib/runner",
    "025_struct_and_errno_and_static_lib/runner",
    "026_goto_and_static_lib/runner",
    "027_ctype_ascii_lib/runner",
    "028_strchr_lib/runner",
    "029_strcspn_lib/runner",
    "030_mutable_buffer_overlap_extrahard_lib/runner",
    "031_disjoint_arrays_lib/runner",
    "032_comma_operator_lib/runner",
    "033_bitfield_lib/runner",
    "034_cast_to_char_ptr_int_lib/runner",
    "035_cast_to_char_ptr_float_lib/runner",
    "036_cast_to_char_ptr_struct_lib/runner",
    "037_cast_to_char_ptr_int_no_strict_aliasing_lib/runner",
    "038_cast_to_char_ptr_float_no_strict_aliasing_lib/runner",
    "039_cast_to_char_ptr_struct_no_strict_aliasing_lib/runner",
    "040_storage_class_auto_lib/runner",
    "041_storage_class_register_lib/runner",
    "042_float_union_lib/runner",
    "043_iso646_and_digraphs_lib/runner",
]
resolver = "2"
