[package]
name = "sphincs-plus-translation"
version = "0.1.0"
edition = "2024"

[lib]
name = "sphincs_plus_translation"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "driver"
path = "src/main.rs"

[features]
default = ["shake", "robust", "192s"]
haraka = []
sha2 = ["dep:sha2"]
shake = ["dep:sha3"]
blake = []
robust = []
simple = []
128f = []
128s = []
192f = []
192s = []
256f = []
256s = []

[dependencies]
aes = "0.8.4"
getrandom = "0.3.3"
sha2 = { version = "0.10.9", features = ["compress"], optional = true }
sha3 = { version = "0.10.8", optional = true }

[dev-dependencies]
libloading = "0.8"

[profile.release]
overflow-checks = false

[workspace]
