[package]
name = "sphincs-plus-translation"
version = "0.1.0"
edition = "2024"

[lib]
name = "sphincs_plus"
path = "src/lib.rs"
crate-type = ["cdylib"]

[[bin]]
name = "driver"
path = "src/main.rs"

[features]
default = ["haraka", "simple", "256f"]

haraka = []
sha2 = []
shake = []
blake = []

robust = []
simple = []

"128s" = []
"128f" = []
"192s" = []
"192f" = []
"256s" = []
"256f" = []

[dependencies]
sha256 = { package = "sha2", version = "0.10.9", features = ["compress"] }
sha3 = "0.10.9"

[profile.release]
overflow-checks = false
panic = "abort"

[workspace]
