[package]
name = "sphincsplus"
version = "0.1.0"
edition = "2021"

[lib]
name = "sphincs_core_det"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "driver"
path = "src/main.rs"

[dependencies]
aes = "0.8"

[features]
default = ["sha2", "simple", "256f"]

# HASH_BACKEND cache variable values
haraka = []
sha2 = []
shake = []
shake256 = ["shake"]
blake = []

# THASH cache variable values
robust = []
simple = []

# SECPAR cache variable values
"128s" = []
"128f" = []
"192s" = []
"192f" = []
"256s" = []
"256f" = []

[profile.release]
opt-level = 3
panic = "abort"

[workspace]
