[package]
name = "sphincsplus"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "driver"
path = "src/main.rs"

[features]
default = ["sha2", "robust", "192s"]
haraka = []
sha2 = []
shake = []
blake = []
robust = []
simple = []
"128s" = []
"128f" = []
"192s" = []
"192f" = []
"256s" = []
"256f" = []

[dependencies]
aes = { version = "0.8", features = ["hazmat"] }

[workspace]
