[package]
name = "sphincsplus"
version = "0.1.0"
edition = "2021"

[lib]
name = "sphincsplus"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "driver"
path = "src/main.rs"

[features]
default = ["blake", "simple", "128f"]
haraka = []
sha2 = []
shake = []
blake = []
robust = []
simple = []
"128f" = []
"128s" = []
"192f" = []
"192s" = []
"256f" = []
"256s" = []

[dependencies]
aes = "0.8"

[profile.release]
opt-level = 3

[workspace]
