[package]
name = "driver"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
libloading = "0.8"

[workspace]

[lib]
name = "driver"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
test = false
doctest = false

[[bin]]
name = "driver"
path = "src/main.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
