[package]
name = "sphincs_plus_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "sha2"
crate-type = ["cdylib"]
path = "src/lib.rs"

[features]
default = ["sha2", "robust", "192f"]

# HASH_BACKEND options
haraka = []
sha2 = []
shake = []
blake = []

# THASH options
robust = []
simple = []

# SECPAR options
"128f" = []
"128s" = []
"192f" = []
"192s" = []
"256f" = []
"256s" = []

[dependencies]
aes = "0.8"

[workspace]
