[package]
name = "c-blind-rsa-signatures"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
openssl-sys = "0.9"
rsa = { version = "0.9", features = ["hazmat"] }
sha2 = "0.10"
num-bigint-dig = { version = "0.8", package = "num-bigint-dig" }
num-traits = "0.2"
num-integer = "0.1"
rand = "0.8"
digest = "0.10"