[package]
name = "impcheck"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.169"

[[bin]]
name = "impcheck_parse"
path = "src/bins/main_parse_bin.rs"

[[bin]]
name = "impcheck_check"
path = "src/bins/main_check_bin.rs"

[[bin]]
name = "impcheck_confirm"
path = "src/bins/main_confirm_bin.rs"
