[package]
name = "sphincs-plus"
version = "0.1.0"
edition = "2021"

[lib]
name = "sphincs_plus"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "driver"
path = "src/main.rs"

[dependencies]
aes = "0.8"

[features]
default = ["shake","simple","192s"]
# Hash backends
blake = []
sha2 = []
shake = []
haraka = []
# Thash variants
simple = []
robust = []
# Security parameter sets
128f = []
128s = []
192f = []
192s = []
256f = []
256s = []

[workspace]
