[package]
name = "sphincs_plus"
version = "0.1.0"
edition = "2021"

[features]
default = ["hash-sha2", "thash-robust", "secpar-128f"]
hash-sha2 = []
hash-blake = []
hash-shake = []
thash-robust = []
thash-simple = []
secpar-128f = []
secpar-128s = []
secpar-192f = []
secpar-192s = []
secpar-256f = []
secpar-256s = []

[dependencies]
sha2 = "0.10"
sha3 = "0.10"
blake = "1.1.2"
aes = "0.8"
digest = "0.10"

[workspace]
