[package]
name = "comma_operator"
version = "0.1.0"
edition = "2021"

[workspace]

[[bin]]
name = "driver"
path = "src/main.rs"
required-features = ["_bin"]

[features]
_bin = []

[lib]
name = "comma_operator"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
libloading = "0.8"
libc = "0.2"
