[package]
name = "sphincsplus"
version = "0.1.0"
edition = "2021"

[lib]
name = "sphincsplus"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "driver"
path = "src/main.rs"

[dependencies]
aes = "=0.8.4"

[features]
# HASH_BACKEND cache variable values
haraka = []
sha2 = []
shake = []
blake = []
# THASH cache variable values
robust = []
simple = []
# SECPAR cache variable values
"128s" = []
"128f" = []
"192s" = []
"192f" = []
"256s" = []
"256f" = []
default = ["haraka", "simple", "192f"]

[profile.release]
opt-level = 3

[workspace]
