[package]
name = "driver"
version = "0.1.0"
edition = "2021"

[lib]
name = "driver"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "driver"
path = "src/main.rs"

[features]
default = ["op_add", "repeat_5"]

# OP cache variable values
op_add = []
op_sub = []
op_mul = []

# REPEAT cache variable values
repeat_0 = []
repeat_1 = []
repeat_2 = []
repeat_3 = []
repeat_4 = []
repeat_5 = []
repeat_6 = []
repeat_7 = []

[workspace]
