[workspace]
members = [
    "053_blake_128f_s_initialize_hash_function_lib/runner",
    "054_blake_128f_s_prf_addr_lib/runner",
    "055_blake_128f_s_gen_message_random_lib/runner",
    "056_blake_128f_s_hash_message_lib/runner",
    "057_blake_128f_r_initialize_hash_function_lib/runner",
    "058_blake_128f_r_prf_addr_lib/runner",
    "059_blake_128f_r_gen_message_random_lib/runner",
    "060_blake_128f_r_hash_message_lib/runner",
    "061_blake_128s_s_initialize_hash_function_lib/runner",
    "062_blake_128s_s_prf_addr_lib/runner",
    "063_blake_128s_s_gen_message_random_lib/runner",
    "064_blake_128s_s_hash_message_lib/runner",
    "065_blake_128s_r_initialize_hash_function_lib/runner",
    "066_blake_128s_r_prf_addr_lib/runner",
    "067_blake_128s_r_gen_message_random_lib/runner",
    "068_blake_128s_r_hash_message_lib/runner",
    "069_blake_192f_s_initialize_hash_function_lib/runner",
    "070_blake_192f_s_prf_addr_lib/runner",
    "071_blake_192f_s_gen_message_random_lib/runner",
    "072_blake_192f_s_hash_message_lib/runner",
    "073_blake_192f_r_initialize_hash_function_lib/runner",
    "074_blake_192f_r_prf_addr_lib/runner",
    "075_blake_192f_r_gen_message_random_lib/runner",
    "076_blake_192f_r_hash_message_lib/runner",
    "077_blake_192s_s_initialize_hash_function_lib/runner",
    "078_blake_192s_s_prf_addr_lib/runner",
    "079_blake_192s_s_gen_message_random_lib/runner",
    "080_blake_192s_s_hash_message_lib/runner",
    "081_blake_192s_r_initialize_hash_function_lib/runner",
    "082_blake_192s_r_prf_addr_lib/runner",
    "083_blake_192s_r_gen_message_random_lib/runner",
    "084_blake_192s_r_hash_message_lib/runner",
    "085_blake_256f_s_initialize_hash_function_lib/runner",
    "086_blake_256f_s_prf_addr_lib/runner",
    "087_blake_256f_s_gen_message_random_lib/runner",
    "088_blake_256f_s_hash_message_lib/runner",
    "089_blake_256f_r_initialize_hash_function_lib/runner",
    "090_blake_256f_r_prf_addr_lib/runner",
    "091_blake_256f_r_gen_message_random_lib/runner",
    "092_blake_256f_r_hash_message_lib/runner",
    "093_blake_256s_s_initialize_hash_function_lib/runner",
    "094_blake_256s_s_prf_addr_lib/runner",
    "095_blake_256s_s_gen_message_random_lib/runner",
    "096_blake_256s_s_hash_message_lib/runner",
    "097_blake_256s_r_initialize_hash_function_lib/runner",
    "098_blake_256s_r_prf_addr_lib/runner",
    "099_blake_256s_r_gen_message_random_lib/runner",
    "100_blake_256s_r_hash_message_lib/runner",
    "101_sha2_128f_s_initialize_hash_function_lib/runner",
    "102_sha2_128f_s_prf_addr_lib/runner",
    "103_sha2_128f_s_gen_message_random_lib/runner",
    "104_sha2_128f_s_hash_message_lib/runner",
    "105_sha2_128f_r_initialize_hash_function_lib/runner",
    "106_sha2_128f_r_prf_addr_lib/runner",
    "107_sha2_128f_r_gen_message_random_lib/runner",
    "108_sha2_128f_r_hash_message_lib/runner",
    "109_sha2_128s_s_initialize_hash_function_lib/runner",
    "110_sha2_128s_s_prf_addr_lib/runner",
    "111_sha2_128s_s_gen_message_random_lib/runner",
    "112_sha2_128s_s_hash_message_lib/runner",
    "113_sha2_128s_r_initialize_hash_function_lib/runner",
    "114_sha2_128s_r_prf_addr_lib/runner",
    "115_sha2_128s_r_gen_message_random_lib/runner",
    "116_sha2_128s_r_hash_message_lib/runner",
    "117_sha2_192f_s_initialize_hash_function_lib/runner",
    "118_sha2_192f_s_prf_addr_lib/runner",
    "119_sha2_192f_s_gen_message_random_lib/runner",
    "120_sha2_192f_s_hash_message_lib/runner",
    "121_sha2_192f_r_initialize_hash_function_lib/runner",
    "122_sha2_192f_r_prf_addr_lib/runner",
    "123_sha2_192f_r_gen_message_random_lib/runner",
    "124_sha2_192f_r_hash_message_lib/runner",
    "125_sha2_192s_s_initialize_hash_function_lib/runner",
    "126_sha2_192s_s_prf_addr_lib/runner",
    "127_sha2_192s_s_gen_message_random_lib/runner",
    "128_sha2_192s_s_hash_message_lib/runner",
    "129_sha2_192s_r_initialize_hash_function_lib/runner",
    "130_sha2_192s_r_prf_addr_lib/runner",
    "131_sha2_192s_r_gen_message_random_lib/runner",
    "132_sha2_192s_r_hash_message_lib/runner",
]
resolver = "2"
