[package]
name = "ljmm"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
path = "src/lib.rs"

[[bin]]
name = "test_001"
path = "src/bin/test_001.rs"
test = false

[[bin]]
name = "test_002"
path = "src/bin/test_002.rs"
test = false

[[test]]
name = "test_001"
path = "src/bin/test_001.rs"

[[test]]
name = "test_002"
path = "src/bin/test_002.rs"
harness = false
