[package]
name = "md-driver"
version = "0.1.0"
edition = "2024"

[features]
default = []
add = []
sub = []
mul = []
"0" = []
"1" = []
"2" = []
"3" = []
"4" = []
"5" = []
"6" = []
"7" = []

[lib]
name = "md_driver"
path = "src/lib.rs"
crate-type = ["cdylib"]

[[bin]]
name = "driver"
path = "src/main.rs"

[workspace]
