[package]
name = "translated_rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "driver"
path = "src/main.rs"

[features]
default = ["blake", "robust", "256f"]
haraka = []
sha2 = []
shake = []
shake256 = ["shake"]
blake = []
robust = []
simple = []
128s = []
128f = []
192s = []
192f = []
256s = []
256f = []

[dependencies]
aes = "0.8"
cipher = "0.4"
sha2 = { version = "0.10", features = ["compress"] }
sha3 = "0.10"

[workspace]
