[package]
name = "echo"
version = "0.1.0"
edition = "2021"

[workspace]

[[bin]]
name = "driver"
path = "src/main.rs"

[[bin]]
name = "test_runner"
path = "src/test_runner.rs"

[lib]
name = "echo"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
libloading = "0.8"

[dev-dependencies]
libc = "0.2"
