[package]
name = "libpsbt"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
base64 = "0.21"

[lib]
path = "src/lib.rs"

[[test]]
name = "test_compactsize"
path = "src/bin/test_compactsize.rs"

[[test]]
name = "test_base64"
path = "src/bin/test_base64.rs"

[[test]]
name = "test_psbt"
path = "src/bin/test_psbt.rs"

[[test]]
name = "test_tx"
path = "src/bin/test_tx.rs"

[[test]]
name = "test_cli"
path = "src/bin/test_cli.rs"
