[package]
name = "driver"
version = "0.1.0"
edition = "2021"

[lib]
name = "driver"
path = "src/lib.rs"
crate-type = ["cdylib"]

[[bin]]
name = "driver"
path = "src/main.rs"

[features]
default = ["add", "5"]

# CMake cache variable OP=<value>
add = []
sub = []
mul = []

# CMake cache variable REPEAT=<value>
"0" = []
"1" = []
"2" = []
"3" = []
"4" = []
"5" = []
"6" = []
"7" = []

[profile.release]
panic = "abort"
