[package]
name = "macrodepth"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "driver"
path = "src/main.rs"

[features]
default = ["add", "repeat_5"]
# OP features (exactly one must be selected)
add = []
sub = []
mul = []
# REPEAT features (exactly one must be selected)
repeat_0 = []
repeat_1 = []
repeat_2 = []
repeat_3 = []
repeat_4 = []
repeat_5 = []
repeat_6 = []
repeat_7 = []

[dependencies]
libc = "0.2"

[workspace]
