[workspace]
members = [
    "arity_lib/runner",
    "arrayfunc_lib/runner",
    "betagamma_lib/runner",
    "buffapp_lib/runner",
    "charinbuf_lib/runner",
    "checkshift_lib/runner",
    "cleanup_lib/runner",
    "complexmode_lib/runner",
    "confusion_lib/runner",
    "dataentry_lib/runner",
    "doubleneg_lib/runner",
    "envy_lib/runner",
    "fallcalc_lib/runner",
    "findrep_lib/runner",
    "goto_lib/runner",
    "gotomach_lib/runner",
    "hatch_lib/runner",
    "inreftree_lib/runner",
    "jumpnode_lib/runner",
    "mathop_lib/runner",
    "matrix_mult_lib/runner",
    "matrixsum_lib/runner",
    "maxnmin_lib/runner",
    "memchra2_lib/runner",
    "modeselect_lib/runner",
    "overunder_lib/runner",
    "task_manager_lib/runner",
]
resolver = "2"
