[workspace]
members = [
    "bin2hex_lib/runner",
    "bitwriter_add_lib/runner",
    "collided_lib/runner",
    "colourblind_lib/runner",
    "contrast_ratio_lib/runner",
    "crc16_lib/runner",
    "dequantize_granule_lib/runner",
    "div_euclid_lib/runner",
    "encode_quant_lib/runner",
    "flac_validate_lib/runner",
    "flip_horizontal_lib/runner",
    "float2half_lib/runner",
    "gaussian_kernel_lib/runner",
    "half2float_lib/runner",
    "hdr_bitrate_lib/runner",
    "hdr_compare_lib/runner",
    "hex2bin_lib/runner",
    "hsl_to_rgb_lib/runner",
    "hsv_to_rgb_lib/runner",
    "ima_parse_lib/runner",
    "ldexp_q2_lib/runner",
    "max_size_frame_lib/runner",
    "md5_digest_lib/runner",
    "merge_sort_lib/runner",
    "next_double_lib/runner",
    "normalize_lib/runner",
    "pow43_lib/runner",
    "premultiply_lib/runner",
    "read_side_info_lib/runner",
    "rev16_lib/runner",
    "rgb_to_hsv_lib/runner",
    "synth_pair_lib/runner",
    "tfm_lib/runner",
    "to_barycentric_lib/runner",
    "tritanopia_lib/runner",
    "update_frame_header_lib/runner",
    "update_md5_lib/runner",
    "wcscat_lib/runner",
]
resolver = "2"
