[package]
name = "c-blind-rsa-signatures"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = { version = "0.10" }
openssl-sys = "0.9"
rsa = { version = "0.9", features = ["sha2"] }
num-bigint-dig = { version = "0.8", package = "num-bigint-dig" }
num-traits = "0.2"
num-integer = "0.1"
sha2 = "0.10"
digest = "0.10"
rand = "0.8"
rand_core = "0.6"
once_cell = "1"
