[package]
name = "sphincsplus"
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "driver"
path = "src/main.rs"

[dependencies]
aes = "0.8"

[features]
haraka = []
sha2 = []
shake = []
blake = []
robust = []
simple = []
128s = []
128f = []
192s = []
192f = []
256s = []
256f = []
default = ["sha2", "simple", "128s"]

[dev-dependencies]
libloading = "0.8"

[workspace]
