[package]
name = "Megalania"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"

[lib]
path = "src/lib.rs"

[[test]]
name = "max_heap_test"
path = "src/bin/max_heap_test.rs"

[[test]]
name = "packet_slab_undo_stack_test"
path = "src/bin/packet_slab_undo_stack_test.rs"

[[test]]
name = "substring_enumerator_test"
path = "src/bin/substring_enumerator_test.rs"

[[test]]
name = "test_lzma_packet"
path = "src/bin/test_lzma_packet.rs"

[[test]]
name = "test_lzma_state"
path = "src/bin/test_lzma_state.rs"

[[test]]
name = "test_probability"
path = "src/bin/test_probability.rs"

[[test]]
name = "test_encoder_interface"
path = "src/bin/test_encoder_interface.rs"

[[test]]
name = "test_output_interface"
path = "src/bin/test_output_interface.rs"

[[test]]
name = "test_probability_model"
path = "src/bin/test_probability_model.rs"

[[test]]
name = "test_perplexity_encoder"
path = "src/bin/test_perplexity_encoder.rs"

[[test]]
name = "test_perplexity_table"
path = "src/bin/test_perplexity_table.rs"

[[test]]
name = "test_lzma_header_encoder"
path = "src/bin/test_lzma_header_encoder.rs"

[[test]]
name = "test_lzma_packet_encoder"
path = "src/bin/test_lzma_packet_encoder.rs"

[[test]]
name = "test_range_encoder"
path = "src/bin/test_range_encoder.rs"

[[test]]
name = "test_packet_slab"
path = "src/bin/test_packet_slab.rs"

[[test]]
name = "test_packet_slab_undo_stack"
path = "src/bin/test_packet_slab_undo_stack.rs"

[[test]]
name = "test_max_heap"
path = "src/bin/test_max_heap.rs"

[[test]]
name = "test_substring_enumerator"
path = "src/bin/test_substring_enumerator.rs"

[[test]]
name = "test_packet_enumerator"
path = "src/bin/test_packet_enumerator.rs"

[[test]]
name = "test_file_output"
path = "src/bin/test_file_output.rs"

[[test]]
name = "test_memory_mapper"
path = "src/bin/test_memory_mapper.rs"

[[test]]
name = "test_top_k_packet_finder"
path = "src/bin/test_top_k_packet_finder.rs"

[[test]]
name = "test_packet_slab_neighbour"
path = "src/bin/test_packet_slab_neighbour.rs"
